tenakata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("university.urls")),
]

university/urls.py
from django.urls import path
from .views import home_page, RegistrationView, admit_list_view, delete_register, UpdateView
# from .views import home_page, RegistrationView, AdminListView

app_name = 'tenakata'

urlpatterns = [
    path('', home_page, name="homepage"),
    path('register/', RegistrationView.as_view(), name="register_page"),
    path('list/', admit_list_view, name="list_page"),
    path('update/<int:pk>', UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', delete_register, name='delete'),
]

university/models.py
from django.db import models
from django_countries.fields import CountryField

# Create your models here.
class Registration(models.Model):
    MARITAL_STATUS = (
        ('single','single'),
        ('married','married')
    )

    GENDER = (
        ('male','male'),
        ('female','female')
    )

    name = models.CharField(max_length=200)
    age = models.IntegerField()
    marital_status = models.CharField(max_length=10, choices=MARITAL_STATUS)
    gender = models.CharField(max_length=10, choices=GENDER)
    height = models.FloatField()
    gsp_location = CountryField(blank_label='select country')
    cam_photo = models.ImageField(upload_to='images')
    iq_test = models.IntegerField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #     if self.age < 1 and self.height < 1:
    #         raise ValueError('Value cannot be -ve')
    #     super(Registration, self).save(*args, **kwargs)

    # class Meta:
    #     ordering = ["iq_test"]

university/forms.py
from django import forms
from .models import Registration
from django_countries.widgets import CountrySelectWidget



class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = '__all__'
        widgets = {'gsp_location': CountrySelectWidget()}
        labels = {
            'name':'Full Names',
            'height':'Height (feet)',
            'gsp_location':'Location'
        }

university/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import RegistrationForm
from django.contrib.messages.views import SuccessMessageMixin
from .models import Registration
import datetime


# Homepage View.
def home_page(request):
    return render(request, "university/home.html")


# Registration View
class RegistrationView(CreateView):
    model = Registration
    form_class = RegistrationForm
    template_name = 'university/register_form.html'
    success_url = reverse_lazy("tenakata:list_page")





#
#
# def RegistrationView(request):
#     error = ""
#     if request.method == "POST":
#         registration_form = RegistrationForm(data = request.POST)
#         if registration_form.is_valid():
#             student = registration_form.save(commit=False)
#             if student.age < 1:
#
#         else:
#             error = 'form error'
#     else:
#         registration_form = RegistrationForm()
#     context = {
#         'error': error,
#         'registration_form': registration_form
#     }
#     return render(request, 'university/register_form.html', context)


# Admission Edit View
class UpdateView(UpdateView):
    model = Registration
    template_name = 'university/update_view.html'
    fields = '__all__'
    success_url = reverse_lazy('tenakata:list_page')


# All registered student view
def admit_list_view(request):
    names = Registration.objects.all()
    admissibility = []
    lists = []
    age = []
    gender = []
    others = []
    unqualified = []
    for name in names:
        if name.age >= 43 and name.iq_test > 100 and name.gender == 'female':
            age.insert(0, name)

        elif name.age >= 43 and name.iq_test > 100 and name.gender == 'male':
            age.insert(-1, name)

        elif name.age >= 26 and name.iq_test > 100 and name.gender == 'female':
            gender.insert(0, name)

        elif name.age >= 26 and name.iq_test > 100 and name.gender == 'male':
            gender.insert(-1, name)

        elif name.age < 26 and name.iq_test > 100 and name.gender == 'female':
            others.insert(0,name)

        elif name.age < 26 and name.iq_test > 100 and name.gender == 'male':
            others.append(name)
        else:
            unqualified.append(name)

    lists.append(age)
    lists.append(gender)
    lists.append(others)

    for list in lists:
        for name in list:
            admissibility.append(name)

    context = {
        'admissibility':admissibility
    }
    return render(request, 'university/admit_list.html', context)


# Delete Student View
def delete_register(request, pk=None):
    Registration.objects.filter(id=pk).delete()
    return redirect('tenakata:list_page')

templates/footer.html
<style>
    footer{
    bottom: 0;
    width: 100%;
    border-top: 1px solid #ccc;
    margin-top: 10px;
    background: teal;
    }
    @media(max-width: 680px){
    footer{
    width: 100%;
    }
    }
    @media(max-width: 300px){
    footer{
    width: 300px;
    }
    }

</style>
<footer>
    <h4 class="p-5 d-flex justify-content-center">&copy;Ambrose 2022 </h4>
</footer>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo.jpg' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css" integrity="sha512-Oy+sz5W86PK0ZIkawrG0iv7XwWhYecM3exvUtMKNJMekGFJtVAhibhRPTpmyTj8+lJCkmWfnpxKgT2OopquBHA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css" />

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script>

    <title>{% block title %}{% endblock %}</title>

    <script>
        $(document).ready(function() {
            $('#example').DataTable( {
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            } );
        } );
    </script>

    <style>
        *{
        margin: 0;
        padding: 0;
        }

        body::before{
        display: block;
        content: " ";
        height: 60px;
        }


    </style>
</head>

<body>
{% include "navbar.html" %}
{% block content %}

{% endblock %}
{% include "footer.html" %}


</body>
</html>

templates/navbar.html
<style>
	img{
	height: 40px;
	width: 40px;
	padding-right: 5px;
	}


	.add-link{
	font-weight: bold;
	display: flex;
	background: teal;
	padding: 10px;
	border-radius: 5px;

	}


	.add-link small:hover{
	color: silver;
	}

	.list-view{
	padding-left: 4px;
	}
	.bi bi-file:hover{
	color: silver;
	}

	@media(max-width: 680px){
	.topnav{
    width: 100%;
    }
    .list-view{
    font-size: 14px;
    }
    }

    @media(max-width: 300px){
    .topnav{
    width: 100%;
    }
    .list-view{
    font-size: 12px;
    }
    }




</style>

<nav class="topnav navbar navbar-expand-lg navbar-dark bg-danger fixed-top">
	{% load static %}
	<div class="container">
		<a class="navbar-brand d-flex align-items-center" href="{% url 'tenakata:homepage' %}"><img src="{% static 'images/logo.jpg' %}" /><strong class="d-none d-sm-block">TENAKATA_UNI</strong></a>
		<a class="navbar-brand text-light  add-link" href="{% url 'tenakata:list_page' %}"><i class="bi bi-file-earmark-text"></i><small class="list-view d-flex align-items-center">View Admission List</small></a>
	</div>
</nav>

university/templates/university/admit_list.html
{% extends "index.html" %}
{% block title %}List{% endblock %}
{% block content %}
{% load static %}

<style>
  @media(max-width: 680px){
	.table-cont{
    font-size: 10px;
    overflow-x: scroll;

    }
    #example_filter{
    display: flex;
    }

    }
</style>
<div class="container">
  <h1>Admissibility List</h1>
</div>


<div class="p-5 pt-0 mt-2 table-cont">
  <table class="table"  id="example" style="width:100%">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Gender</th>
        <th scope="col">Marital Status</th>
        <th scope="col">Height(Inches)</th>
        <th scope="col">Location</th>
        <th scope="col">Photo</th>
        <th scope="col">IQ Test</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>

      <tbody>
      {% for name in admissibility %}
      <tr>
        <th scope="row">{{ forloop.counter }}.</th>
        <td>{{ name.name }}</td>
        <td>{{ name.age }}</td>
        <td>{{ name.gender }}</td>
        <td>{{ name.marital_status }}</td>
        <td>{{ name.height }}</td>
        <td>{{ name.gsp_location }}</td>
        <td><img src="{{ name.cam_photo.url }}"</td>
        <td>{{ name.iq_test }}</td>
        <td><a href="{% url 'tenakata:update' name.id %}"><i class="bi bi-pencil-square text-success"></i></a></td>
        <td><a href="{% url 'tenakata:delete' name.id %}"><i class="bi bi-trash text-danger" onclick="return confirm('Do you want to {{ name.name }}?')"></i></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock %}

university/templates/university/home.html
{% extends "index.html" %}
{% block title %}Tenakata University{% endblock %}
{% block content %}
{% load static %}
<style>
    .home-container{
    height: 90vh;
    background-image: url("{% static 'images/banner2.jpg' %}");
    background-size: cover;

    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    color: teal;
    font-weight: bold;
    }

    .content-container div{
     display: flex;
     flex-direction: column;
     justify-content: center;
     align-items: center;
     border-radius: 10px;
     background: black;
    }

    .button_enroll{
    background: teal;
    padding: 10px;
    border-radius: 5px;
    color: black;
    text-decoration: unset;
    }

    .button_enroll:hover{
    background: crimson;
    color: #fff;
    }

    h1{
    font-size: 52px;
    }

    @media(max-width: 1080px){
    h1{
    font-size: 48px;
    margin-bottom: 15px;
    }
    p{
    font-size: 20px;
    margin-bottom: 15px;
    }
    .button_enroll{
    font-size: 20px;
    display: flex;
    justify-content: start;
    }
    .content-container div{
     display: flex;
     flex-direction: column;
     justify-content: start;
     align-items: start;
     border-radius: 10px;
     background: black;
    }
    }



    @media(max-width: 680px){
    h1{
    font-size: 25px;
    }
    p{
    font-size: 12px;
    }
    .button_enroll{
    font-size: 12px;
    display: flex;
    justify-content: start;
    }
    .content-container div{
     display: flex;
     flex-direction: column;
     justify-content: start;
     align-items: start;
     border-radius: 10px;
     background: black;
    }
    }

    @media(max-width: 350px){
    h1{
    font-size: 25px;
    margin-bottom: 15px;
    }
    p{
    font-size: 12px;
    margin-bottom: 25px;
    }
    .button_enroll{
    font-size: 12px;
    display: flex;
    justify-content: start;
    }
    .content-container div{
     display: flex;
     flex-direction: column;
     justify-content: start;
     align-items: start;
     border-radius: 10px;
     background: black;
    }
    }



</style>

<div class="home-container">
    <div class="content-container d-flex align-items-center justify-content-center h-100 ">
        <div class="content text-white p-5 ">
            <h1 class="text-white">Welcome to <span style="color: crimson">Tena</span><span style="color:teal">kata</span> University</h1>
            <P style="color: teal;"><i>"Setting Trends in Higher Education, Research, Innovation and Entrepreneurship"</i></P>
            <a href="{% url 'tenakata:register_page' %}" class="button_enroll btn-lg animate__animated animate__bounceIn text-white">Enroll now</a>
        </div>
    </div>
</div>
{% endblock %}

university/templates/university/register_form.html
{% extends "index.html" %}
{% block title %}Enrolment Form{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<style>
    .form-container{
    width: 800px;
    }

    .form-group{
    margin-bottom: 30px;
    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    color: teal;
    font-weight: bold;
    font-size: 18px;
    }


    .btn:hover{
    background: teal;
    color: black;
    }

    @media(max-width: 680px){
    h1{
    font-size: 18px;
    }
    .form-container{
    width: 90%;
    margin: auto;
    }
    label{
    font-size: 12px;
    }
    }


</style>

<div class="container form-container">
    <h1 class="mt-3 mb-3 text-center">Fill in the Registration form below</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" id="btn-reg" class="btn btn-danger mt-3 btnu" onclick="validation()">Register</button>
    </form>
</div>
<script>
    var age = document.getElementById("id_age")
    age.addEventListener('keyup', buttAge)
    var iq = document.getElementById("id_iq_test")
    iq.addEventListener('keyup', iqTest)
    var height = document.getElementById("id_height")
    height.addEventListener('keyup', Height)
    var button = document.getElementById("btn-reg")
    var loc = document.getElementById("id_gsp_location")
    loc.addEventListener('input', country)


    function buttAge(e){
        val = e.target.value
        if(val < 18){
            button.style.display = 'none';
            age.style.border = '1px solid red';
        }else{
            button.style.display = 'block';
            age.style.border = '1px solid #ced4da';
        }
    }

    function iqTest(e){
        val = e.target.value
        if(val < 0){
            button.style.display = 'none';
            iq.style.border = '1px solid red';
        }else{
            button.style.display = 'block';
            iq.style.border = '1px solid #ced4da';
        }
    }

    function Height(e){
        val = e.target.value
        if(val < 1){
            button.style.display = 'none';
            height.style.border = '1px solid red';
        }else{
            button.style.display = 'block';
            height.style.border = '1px solid #ced4da';
        }
    }

    function country(e){
        var selected = loc.options[loc.selectedIndex].text
        if(selected !== "Kenya"){
            button.style.display = 'none';
            alert("Sorry only Kenyan Nationalities Allowed!")
        }else{
            button.style.display = 'block';
        }
    }

</script>
{% endblock %}

university/templates/university/update_view.html
{% extends "index.html" %}
{% block title %}Update{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    width: 800px;
    }

    .form-group{
    margin-bottom: 30px;
    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    color: teal;
    font-weight: bold;
    font-size: 18px;
    }


    .btn:hover{
    background: teal;
    color: black;
    }


</style>

<div class="container form-container">
    <h1 class="mt-3 mb-3 text-center">Update <span style="font-weight: 400; font-style: italic">{{ object.name }}</span> details</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" id="btn-reg" class="btn btn-danger mt-3 btnu">Update</button>
    </form>
</div>

{% endblock %}